controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true
    
    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffbot_base_controller:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['Left_wheel_joint']
    right_wheel_names: ['Right_wheel_joint']
    wheel_separation: 0.9
    wheel_radius: 0.126

    use_stamped_vel: false